# Generated by Django 4.2.10 on 2024-03-15 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stories', '0004_delete_wordsmithuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordsmithUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Bio', models.TextField(max_length=4000, verbose_name='Bio')),
                ('Stories', models.ManyToManyField(blank=True, to='stories.story')),
            ],
        ),
    ]
