# Generated by Django 4.2.10 on 2024-03-15 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordsmithuser',
            name='Name',
            field=models.CharField(max_length=20, verbose_name='Name'),
        ),
    ]
