# Generated by Django 4.2.10 on 2024-03-12 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=20, verbose_name='Title')),
                ('Blurb', models.CharField(blank=True, max_length=200, verbose_name='Blurb')),
                ('Content', models.TextField(max_length=50000, verbose_name='Short Story')),
            ],
        ),
        migrations.CreateModel(
            name='WordsmithUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20, verbose_name='User Email')),
            ],
        ),
    ]
