# Generated by Django 4.2.10 on 2024-03-15 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_story_auther'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WordsmithUser',
        ),
    ]
