# Generated by Django 4.2.10 on 2024-03-17 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0004_delete_wordsmithuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='Story_Cover',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
