# Generated by Django 4.2.10 on 2024-03-17 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0005_story_story_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='Blurb',
            field=models.TextField(blank=True, max_length=200, verbose_name='Blurb'),
        ),
    ]
