# Generated by Django 4.2.10 on 2024-03-23 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0008_alter_story_story_cover'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='Auther',
            new_name='auther',
        ),
        migrations.RenameField(
            model_name='story',
            old_name='Blurb',
            new_name='blurb',
        ),
        migrations.RenameField(
            model_name='story',
            old_name='Content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='story',
            old_name='Story_Cover',
            new_name='story_cover',
        ),
        migrations.RenameField(
            model_name='story',
            old_name='Title',
            new_name='title',
        ),
    ]
